### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by WangPenglei717** [wujialu/MF-SuP-pKa#3]
Thank you for sharing this work!  In the process of using the dataset, I have a few questions:
    1. How do you split the dataset into acidic and basic types? 
    2. Can you share the script or tool used to divide the data? 
I look forward to your answers! Thank you very much for your help !

**Comment by wujialu** [comment]
Thank you for your interest in the work. 
I split the dataset into acidic and basic types in two steps:
1. For the ChEMBL dataset, I split the molecule into acidic (basic) set if it contain predicted acidic (basic) pKa values. As for the DataWarrior dataset, I split the molecule into acidic (basic) set if it contain experimental acidic (basic) pKa values.
2. In each subset, the molecules without detectable ionization sites were removed.

**Comment by WangPenglei717** [comment]
Thank you for your reply! @wujialu 
When we are ready to make a prediction for a new molecule, how do we decide whether to use the acidic model or the basic model for prediction?

**Comment by wujialu** [comment]
You can use the  `get_ionization_aid` function in [https://github.com/wujialu/MF-SuP-pKa/blob/main/MF_SuP_pka/ionization_group.py](url)
If the molecule has detectable acidic (basic) sites, you can use the acidic (basic) model for prediction.

**Comment by WangPenglei717** [comment]
Hello, I am trying to use `get_ionization_aid` function to determine which model for prediction, but when I process the molecule `O=C(CNC(=O)c1ccccc1)Nc1nc2ccccc2s1`, the function determines that the acidic site is [3, 12] and the basic site is [12, 14], in which case I am not sure which model to use. Could you please give more detailed criteria for the determination? Thank you very much for your help ! @wujialu

**Comment by wujialu** [comment]
For those amphoteric molecules having both acidic and basic sites, you should use the acidic model to predict the acidic pKa, and use the basic model to predict the basic pKa. The acidic pKa measures the de-protonation process, while the basic pKa measures the protonation process. @WangPenglei717

**Comment by WangPenglei717** [comment]
I see, thank you very much for your help ! @wujialu
